package com.bookbuddy.bookbuddy.entities;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Schema(name = "GuestOrder", description = "Order made by a guest")
@Table(name = "guest_orders")
public class GuestOrder {

    @Id
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Unique ID generated by database corresponding to a user", example = "1")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long orderId;

    @Column(name = "guest_name")
    @Schema(description = "Full name of the guest who placed the order", example = "John Doe")
    private String guestName;

    @Schema(description = "Email of the guest who placed the order", example = "example@email.com")
    @Column(name = "guest_email")
    private String guestEmail;

    @Schema(description = "Total amount of the order", example = "19.99")
    @Column(name = "total_amount")
    private double totalAmount;

    @Schema(description = "Shipping address of the guest who placed the order", example = "123 Main Street Example, Arizona 11111")
    @Column(name = "guest_address")
    private String guestShippingAddress;

    @Column(name = "payment_id")
    private long paymentIntentId;

    @ManyToOne
    @JoinColumn(name = "book_id")
    @Schema(description = "The id of the book that was ordered", example = "1")
    private Book book;

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public String getGuestEmail() {
        return guestEmail;
    }

    public void setGuestEmail(String guestEmail) {
        this.guestEmail = guestEmail;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public long getPaymentIntentId() {
        return paymentIntentId;
    }

    public void setPaymentIntentId(long paymentIntentId) {
        this.paymentIntentId = paymentIntentId;
    }

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public String getGuestShippingAddress() {
        return guestShippingAddress;
    }

    public void setGuestShippingAddress(String guestShippingAddress) {
        this.guestShippingAddress = guestShippingAddress;
    }

    public String getGuestName() {
        return guestName;
    }

    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }
}
